# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
from spaghetti import q_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [4]:
weather=pd.read_csv('weath_er.csv')
weath_er=weather.drop(['Unnamed: 0'], axis=1)
weath_er.head(2)

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
0,Tuktoyaktuk,90,CA,1580836288,75,69.45,-133.04,-18.400,5.70
1,Umm Lajj,0,SA,1580836289,64,25.02,37.27,62.708,2.25

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [5]:
gmaps.configure(api_key=q_key)
locations=weath_er[["Lat", "Lng"]]
weight=weath_er["Humidity"].astype(float)
fig=gmaps.figure()
heat_layer=gmaps.heatmap_layer(locations, weights=weight, 
                                 dissipating=True, max_intensity=10,
                                 point_radius=1)
fig.add_layer(heat_layer)
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [18]:
nice_weather=weath_er[weath_er['Max Temp'] > 65]
nicer_weather=nice_weather[nice_weather['Max Temp'] < 90]
nicest_weather=nicer_weather[nicer_weather['Humidity'] < 50]
best_weather=nicest_weather[nicest_weather['Wind Speed'] > 5]
best_weather

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
2,Miraflores,40,MX,1580836289,42,19.22,-98.81,73.400,7.70
18,Pisco,12,PE,1580836191,30,-13.70,-76.22,78.008,6.70
25,Busselton,0,AU,1580836304,25,-33.65,115.33,78.008,8.36
85,Aguimes,54,ES,1580836336,19,27.91,-15.45,78.800,5.10
248,Moussoro,17,TD,1580836438,10,13.64,16.49,75.398,5.48
251,Monte Patria,0,CL,1580836440,19,-30.69,-70.95,82.220,5.88
264,Nouadhibou,0,MR,1580836448,26,20.93,-17.03,84.200,6.20
334,San Rafael,5,AR,1580836487,34,-34.62,-68.33,82.346,7.82
342,Upington,40,ZA,1580836492,27,-28.45,21.26,87.800,7.70
387,Illapel,0,CL,1580836518,27,-31.63,-71.17,75.650,5.41
408,Ovalle,0,CL,1580836529,19,-30.60,-71.20,82.220,5.88
414,Havelock,40,US,1580836534,40,34.88,-76.90,73.004,7.20
422,Umm Kaddadah,39,SD,1580836540,13,13.60,26.69,70.124,5.09
426,Safaga,0,EG,1580836542,42,26.73,33.94,68.000,5.10
527,Arona,20,ES,1580836598,43,28.10,-16.68,77.000,5.10

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [19]:
hotel_df=best_weather
hotel_df['Hotel Name']=['','','','','','','','','','','','','','','']

C:\Users\phili\Anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in narrowed_city_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [ ]:
# Add marker layer ontop of heat map


# Display Map